### ISSUE TITLE
关于注释和论文

### ISSUE THREAD

**Issue by polarisZhao** [666DZY666/model-compression#9]
您好， 非常感谢您的分享。不过比较遗憾的是你的代码中注释很少，也没有相关的论文。能否把代码相关的论文附上， 以便大家学习。谢谢

**Comment by 666DZY666** [comment]
WbWtAb文件夹中的代码注释相对详细一些，其他代码仅注释了一些比较关键的地方；
相关论文随后会附上，谢谢

**Comment by zyc4me** [comment]
同求一些参考论文 来学习，只看代码不理解。。 另外，作者大大，实在是太厉害了 ，强强👍

**Comment by JensenHJS** [comment]
希望作者可以尽快分享一些跟代码里思想一样的论文，期待，感谢

**Comment by 666DZY666** [comment]
已补充至readme
